---
title: "firstRFolder"
author: "Ozi"
date: "11/25/2021"
output: pdf_document
---

```{r}

34 + 5
```

```{r}

x <- {1: 235 }
x
```
```{r}

x <- 1:3
y <- 4:6

cbind(x,y)
rbind(x, y)
```

```{r}
mat <- matrix(1:4, nrow = 2, ncol=2)
colnames(mat) <- c("a", "b")
rownames(mat)<- c("c", "d")
mat

```

```{r}
x = c(1:4)
y = c(5:8)

m = cbind(x, y)
m

q = rbind(x, y)
q


colnames(m)
rownames(m)

colnames(q)
rownames(q)
```

```{r}
emp.data<- data.frame(emp_id = c (1:5),
                      emp_name = c("Damilola", "Ay", "Mojoyin", "Toska", "Fati"),
                      emp_salary = c(4.2, 3.2, 5, 2.8, 7.1))
 
emp.data
emp.data$emp_id
emp.data$emp_name
emp.data$emp_name[3]
```

```{r}
x <- 5:7
names(x)

names(x)<-c("five", "six", "seven")
names(x)
x
```

```{r}
x<- matrix(1:6, 2,3)
x[2,3]

```


```{r}
x<-matrix(1:12, 3, 4)
x

x[2:3, 2:4]

```
```{r}
x<- matrix(1:6, 2,3)
x
x[1,2]

x[1, 2, drop= FALSE]
x[1,,drop=FALSE]
x[,2, drop=FALSE]
```

```{r}
y = matrix(1:16, 4,4)
y

y[1:3, 3:4]

colnames(y)<- c("1st", "2nd", "3rd", "4th")
y
y[1,2]
#y
```
