---
title: "databaseConnection"
author: "Ozi"
date: "11/30/2021"
output: pdf_document
---

```{r}
host<- "courses.csrrinzqubik.us-east-1.rds.amazonaws.com"
connect<-dbConnect(RMySQL::MySQL(), dbname="tweater",
                   host = host, port= 3306, user = "student", password="datacamp")


```

```{r}
tables<- dbListTables(connect)
tables
```
```{r}
users <- dbReadTable(connect, "users")
users
```

```{r}
write.csv(comments, "comments.csv")
```

```{r}
host<- "car-simulation-station.c9az8e0qjbgo.us-east-1.rds.amazonaws.com"
connect <- dbConnect(RMySQL::MySQL(),dbname="car_simulation_station",
                     host= host, port=3306, user="datacamp_user",
                     password="learn tabular data for fun and profit")
```
```{r}
tables<- dbListTables(connect)
tables
```

```{r}
home_cleaned <- dbReadTable(connect, "adhd_home_cleaned")
home_cleaned
```


```{r}

report_cleaned <- dbReadTable(connect, "bapq_father_self_report_cleaned")
report_cleaned
```
```{r}
scq_cleaned<-dbReadTable(connect, "lifetime_scq_cleaned")
scq_cleaned
```

```{r}
write.csv(home_cleaned, "home_cleaned.csv")
```

```{r}
write.csv(report_cleaned, "report_cleaned.csv")

```


```{r}
write.csv(scq_cleaned, "scq_cleaned.csv")

```


```{r}
bcancer<- read.csv("https://raw.githubusercontent.com/mGalarnyk/Python_Tutorials/master/Kaggle/BreastCancerWisconsin/data/data.csv", header=TRUE)

str(bcancer)
```


```{r}
house<- read.csv("~/house.csv", sep=",")
house
boxplot(Price~Status, data = house, main="Price")
plot(house$SQFT, house$Price, xlab="SQFT", ylab="Price", main="ScatterPlot of Price and SQFT")
```
```{r}
hist(house$Price,xlab = "Price", main="Histogram")
```

```{r}
child_data <- read_sav("~/child_data.sav")
child_data
```


```{r}
cancer_info <- read.csv("~/cancer.csv", sep =",")
cancer_info

```


```{r}
sum(is.na(child_data))
```


```{r}
sum(is.na(cancer_info))
```


```{r}

boxplot(MEM_SPAN~AGE, data = child_data, main="Age")
plot(child_data$AGE, child_data$MEM_SPAN, xlab="AGE", ylab="MEM_SPAN", main="ScatterPlot of Age and IQ")
```
```{r}
library(readxl)
library(tidyverse)
```

```{r}
mbta1<- read_excel("~/mbta.xlsx", sheet =1, skip = 1, range= cell_cols(2:60))
mbta1
```

```{r}
mbta<- mbta1%>% gather(`2007-01`:`2011-10`, key = "year", value = "passenger")
mbta

```

```{r}

```

```{r}

```